{% set name = "pytest-remote-response" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-remote-response-{{ version }}.tar.gz
  sha256: 566acf5399fdb07383e31da3cff7b0973d4e2d371dba883bc2530954bb70cd29

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=4.6
    - requests >=2.25.1
    - aiohttp

test:
  imports:
    - pytest_response
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/devanshshukla99/pytest-remote-response
  summary: Pytest plugin for capturing and mocking connection requests.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - devanshshukla99
